"""Bind the Robobus117th visible PIX mesh to the hidden stable VehicleMesh pose.

Run from UE4.26 with CARLA's ``CarlaUE4.uproject`` after the stable
``BP_Robobus117th`` exists. The blueprint already contains a visible
``PixVisualMesh1`` component generated by UE4's construction/template system.
This helper edits that existing component instead of adding a new component,
which keeps the stable Fuso ``VehicleMesh`` available for CARLA physics while
the PIX visual mesh copies the animated wheel pose.

The default target mesh is the PIX import that uses the Mitsubishi FusoRosa
skeleton. It is required for ``set_master_pose_component`` to drive visible
wheel pose from the hidden carrier animation blueprint.
"""

from __future__ import annotations

import os

import unreal  # type: ignore


PREFIX = "ZMF_ROBOBUS_COPYPOSE "

BP_ASSET = os.environ.get(
    "ROBOBUS_BP_ASSET",
    "/Game/Carla/Blueprints/Vehicles/PixMoving/Robobus117th/BP_Robobus117th",
)
BP_CLASS = os.environ.get("ROBOBUS_BP_CLASS", BP_ASSET + ".BP_Robobus117th_C")
VEHICLE_FACTORY = os.environ.get(
    "ROBOBUS_VEHICLE_FACTORY",
    "/Game/Carla/Blueprints/Vehicles/VehicleFactory",
)
ROOT_MESH_PROPERTY = os.environ.get("ROBOBUS_ROOT_MESH_PROPERTY", "mesh")
PIX_VISUAL_COMPONENT = os.environ.get(
    "ROBOBUS_PIX_VISUAL_COMPONENT",
    BP_ASSET + ".BP_Robobus117th_C:PixVisualMesh1_GEN_VARIABLE",
)
PIX_VISUAL_MESH = os.environ.get(
    "ROBOBUS_PIX_VISUAL_MESH",
    (
        "/Game/Carla/Static/Vehicles/4Wheeled/Robobus117thFusoSkelScale1/"
        "SKM_robobus117th_axis_safe."
        "SKM_robobus117th_axis_safe_robobus_part_000_Object_________1_6"
    ),
)
VISUAL_OFFSET_X = float(os.environ.get("ROBOBUS_PIX_VISUAL_OFFSET_X", "0.0"))
VISUAL_OFFSET_Y = float(os.environ.get("ROBOBUS_PIX_VISUAL_OFFSET_Y", "0.0"))
VISUAL_OFFSET_Z = float(os.environ.get("ROBOBUS_PIX_VISUAL_OFFSET_Z", "0.0"))
VISUAL_ROTATION_PITCH = float(os.environ.get("ROBOBUS_PIX_VISUAL_ROTATION_PITCH", "0.0"))
VISUAL_ROTATION_YAW = float(os.environ.get("ROBOBUS_PIX_VISUAL_ROTATION_YAW", "0.0"))
VISUAL_ROTATION_ROLL = float(os.environ.get("ROBOBUS_PIX_VISUAL_ROTATION_ROLL", "0.0"))
VISUAL_SCALE = float(os.environ.get("ROBOBUS_PIX_VISUAL_SCALE", "1.0"))


def log(message: object) -> None:
    print(PREFIX + str(message))


def load_required_object(path: str):
    obj = unreal.load_object(None, path)
    if not obj:
        raise RuntimeError(f"Could not load object: {path}")
    return obj


def object_path(obj: object) -> str:
    if obj is None:
        return "None"
    try:
        return obj.get_path_name()
    except Exception:
        return str(obj)


def get_optional_editor_property(obj: object, prop: str):
    try:
        return obj.get_editor_property(prop)
    except Exception as exc:
        log(f"GET_SKIP {object_path(obj)}.{prop}: {exc}")
        return None


def save_asset(path: str) -> None:
    try:
        ok = unreal.EditorAssetLibrary.save_asset(path, only_if_is_dirty=False)
    except TypeError:
        ok = unreal.EditorAssetLibrary.save_asset(path)
    log(f"SAVE {path} ok={ok}")
    if not ok:
        raise RuntimeError(f"Failed to save asset: {path}")


def main() -> None:
    bp_cls = load_required_object(BP_CLASS)
    cdo = unreal.get_default_object(bp_cls)
    root_mesh = cdo.get_editor_property(ROOT_MESH_PROPERTY)
    visual = load_required_object(PIX_VISUAL_COMPONENT)
    pix_mesh = load_required_object(PIX_VISUAL_MESH)

    old_visual_mesh = get_optional_editor_property(visual, "skeletal_mesh")
    old_master = get_optional_editor_property(visual, "master_pose_component")
    old_hidden = get_optional_editor_property(visual, "hidden_in_game")
    old_visible = get_optional_editor_property(visual, "visible")
    old_location = get_optional_editor_property(visual, "relative_location")
    old_rotation = get_optional_editor_property(visual, "relative_rotation")
    old_scale = get_optional_editor_property(visual, "relative_scale3d")

    visual.set_editor_property("skeletal_mesh", pix_mesh)
    visual.set_editor_property("hidden_in_game", False)
    visual.set_editor_property("visible", True)
    visual.set_editor_property("relative_location", unreal.Vector(VISUAL_OFFSET_X, VISUAL_OFFSET_Y, VISUAL_OFFSET_Z))
    visual.set_editor_property(
        "relative_rotation",
        unreal.Rotator(
            pitch=VISUAL_ROTATION_PITCH,
            yaw=VISUAL_ROTATION_YAW,
            roll=VISUAL_ROTATION_ROLL,
        ),
    )
    visual.set_editor_property("relative_scale3d", unreal.Vector(VISUAL_SCALE, VISUAL_SCALE, VISUAL_SCALE))
    visual.set_collision_enabled(unreal.CollisionEnabled.NO_COLLISION)
    visual.set_master_pose_component(root_mesh, False)
    visual.add_tick_prerequisite_component(root_mesh)

    save_asset(BP_ASSET)
    save_asset(VEHICLE_FACTORY)

    new_visual_mesh = get_optional_editor_property(visual, "skeletal_mesh")
    new_master = get_optional_editor_property(visual, "master_pose_component")
    new_hidden = get_optional_editor_property(visual, "hidden_in_game")
    new_visible = get_optional_editor_property(visual, "visible")
    new_location = get_optional_editor_property(visual, "relative_location")
    new_rotation = get_optional_editor_property(visual, "relative_rotation")
    new_scale = get_optional_editor_property(visual, "relative_scale3d")

    log(f"BLUEPRINT={BP_ASSET}")
    log(f"ROOT_MESH={object_path(root_mesh)}")
    log(f"ROOT_SKELETAL_MESH={object_path(get_optional_editor_property(root_mesh, 'skeletal_mesh'))}")
    log(f"VISUAL_COMPONENT={PIX_VISUAL_COMPONENT}")
    log(f"VISUAL_MESH_BEFORE={object_path(old_visual_mesh)}")
    log(f"VISUAL_MESH_AFTER={object_path(new_visual_mesh)}")
    log(f"MASTER_BEFORE={object_path(old_master)}")
    log(f"MASTER_AFTER={object_path(new_master)}")
    log(f"HIDDEN_BEFORE={old_hidden} HIDDEN_AFTER={new_hidden}")
    log(f"VISIBLE_BEFORE={old_visible} VISIBLE_AFTER={new_visible}")
    log(f"LOCATION_BEFORE={old_location} LOCATION_AFTER={new_location}")
    log(f"ROTATION_BEFORE={old_rotation} ROTATION_AFTER={new_rotation}")
    log(f"SCALE_BEFORE={old_scale} SCALE_AFTER={new_scale}")
    log("DONE")


main()
