#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../../.." && pwd)"
SOURCE_PACKAGE="${SOURCE_PACKAGE:-${REPO_ROOT}/artifacts/carla_blueprints/robobus117th_source}"
OUTPUT_DIR="${OUTPUT_DIR:-${SOURCE_PACKAGE}/unreal_import}"
DAE_PATH="${DAE_PATH:-${SOURCE_PACKAGE}/source/install/robobus_description/mesh/robobus.dae}"

usage() {
  cat <<'USAGE'
Prepare UE4 import inputs for robobus117th.

Options:
  --source-package PATH  Source package generated by prepare_source_package.sh.
  --dae PATH             Explicit DAE mesh path.
  --output-dir PATH      Output directory for UE import files.

Behavior:
  - Always copies the source DAE into the output directory.
  - Uses Blender if available to export robobus.fbx.
  - Uses assimp if available to export robobus.obj as a visual-placeholder fallback.
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --source-package) SOURCE_PACKAGE="$2"; DAE_PATH="$2/source/install/robobus_description/mesh/robobus.dae"; shift 2 ;;
    --dae) DAE_PATH="$2"; shift 2 ;;
    --output-dir) OUTPUT_DIR="$2"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "[FAIL] Unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

mkdir -p "${OUTPUT_DIR}"

if [[ ! -f "${DAE_PATH}" ]]; then
  echo "[FAIL] DAE mesh missing: ${DAE_PATH}" >&2
  echo "[HINT] Run: bash assets/vehicles/robobus117th/scripts/prepare_source_package.sh" >&2
  exit 1
fi

cp -a "${DAE_PATH}" "${OUTPUT_DIR}/robobus.dae"

STATUS_FILE="${OUTPUT_DIR}/conversion_status.txt"
: > "${STATUS_FILE}"
{
  echo "source_package=${SOURCE_PACKAGE}"
  echo "dae_path=${DAE_PATH}"
  echo "output_dir=${OUTPUT_DIR}"
  echo "generated_at=$(date -Iseconds)"
} >> "${STATUS_FILE}"

if command -v blender >/dev/null 2>&1; then
  BLENDER_SCRIPT="${OUTPUT_DIR}/convert_dae_to_fbx.py"
  cat > "${BLENDER_SCRIPT}" <<'PY'
import pathlib
import sys
import bpy

dae_path = pathlib.Path(sys.argv[-2]).resolve()
fbx_path = pathlib.Path(sys.argv[-1]).resolve()

bpy.ops.object.select_all(action="SELECT")
bpy.ops.object.delete()
bpy.ops.wm.collada_import(filepath=str(dae_path))

for obj in bpy.context.scene.objects:
    obj.select_set(True)

bpy.ops.export_scene.fbx(
    filepath=str(fbx_path),
    use_selection=True,
    axis_forward="X",
    axis_up="Z",
    apply_unit_scale=True,
    bake_space_transform=False,
)
PY
  if blender --background --python "${BLENDER_SCRIPT}" -- "${OUTPUT_DIR}/robobus.dae" "${OUTPUT_DIR}/robobus.fbx" >> "${STATUS_FILE}" 2>&1; then
    echo "fbx_status=generated" >> "${STATUS_FILE}"
    echo "[PASS] Generated FBX: ${OUTPUT_DIR}/robobus.fbx"
  else
    echo "fbx_status=failed" >> "${STATUS_FILE}"
    echo "[WARN] Blender conversion failed; see ${STATUS_FILE}"
  fi
else
  echo "fbx_status=skipped_blender_missing" >> "${STATUS_FILE}"
  echo "[WARN] blender missing; FBX was not generated"
fi

if command -v assimp >/dev/null 2>&1; then
  if assimp export "${OUTPUT_DIR}/robobus.dae" "${OUTPUT_DIR}/robobus.obj" >> "${STATUS_FILE}" 2>&1; then
    echo "obj_status=generated" >> "${STATUS_FILE}"
    echo "[PASS] Generated OBJ fallback: ${OUTPUT_DIR}/robobus.obj"
  else
    echo "obj_status=failed" >> "${STATUS_FILE}"
    echo "[WARN] assimp conversion failed; see ${STATUS_FILE}"
  fi
else
  echo "obj_status=skipped_assimp_missing" >> "${STATUS_FILE}"
  echo "[WARN] assimp missing; OBJ fallback was not generated"
fi

cat > "${OUTPUT_DIR}/README_UE4_IMPORT_CN.md" <<'README'
# Robobus117th UE4 导入输入

这个目录给 UE4.26/CARLA 0.9.15 车辆资产制作使用。

优先导入：

- `robobus.fbx`，如果 Blender 可用并转换成功。

备选导入：

- `robobus.obj`，如果 assimp 可用并转换成功，只适合视觉占位。
- `robobus.dae`，原始 Autoware/RViz mesh，UE4 不一定能直接可靠导入。

注意：

- DAE 声明 `Z_UP`，root node 有近似 `0.001` 缩放和轴转换矩阵。
- UE4/CARLA 使用 X forward、Y right、Z up；ROS base_link 使用 X forward、Y left、Z up。
- 真正可驾驶车辆还需要 wheel blueprint、collision、physics asset、vehicle movement 参数和 cooked asset。
README

echo "Prepared UE4 import directory: ${OUTPUT_DIR}"
echo "Status: ${STATUS_FILE}"
