#!/usr/bin/env bash
set -euo pipefail

AUTOWARE_WS_ARG=""
PRESET_NAME=""
MODE="route_follow_only"
SNAPSHOT_OUT=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --autoware-ws) AUTOWARE_WS_ARG="$2"; shift 2 ;;
    --preset-name) PRESET_NAME="$2"; shift 2 ;;
    --mode) MODE="$2"; shift 2 ;;
    --snapshot-out) SNAPSHOT_OUT="$2"; shift 2 ;;
    *) echo "Unknown arg: $1" >&2; exit 2 ;;
  esac
done

AUTOWARE_WS="${AUTOWARE_WS_ARG:-${AUTOWARE_WS:-$HOME/zmf_ws/projects/autoware_universe/autoware}}"
if [[ -z "$PRESET_NAME" ]]; then
  echo "--preset-name is required" >&2
  exit 2
fi

PRESET_DIR="${AUTOWARE_WS}/install/autoware_launch/share/autoware_launch/config/planning/preset"
SOURCE_PRESET="${PRESET_DIR}/default_preset.yaml"
TARGET_PRESET="${PRESET_DIR}/${PRESET_NAME}_preset.yaml"
CONTROL_PRESET_DIR="${AUTOWARE_WS}/install/autoware_launch/share/autoware_launch/config/control/preset"
SOURCE_CONTROL_PRESET="${CONTROL_PRESET_DIR}/default_preset.yaml"
TARGET_CONTROL_PRESET="${CONTROL_PRESET_DIR}/${PRESET_NAME}_preset.yaml"

if [[ ! -f "$SOURCE_PRESET" ]]; then
  echo "Default planning preset not found: ${SOURCE_PRESET}" >&2
  exit 1
fi

mkdir -p "$(dirname "$TARGET_PRESET")"
if [[ -n "$SNAPSHOT_OUT" ]]; then
  mkdir -p "$(dirname "$SNAPSHOT_OUT")"
fi

python3 - "$SOURCE_PRESET" "$TARGET_PRESET" "$SOURCE_CONTROL_PRESET" "$TARGET_CONTROL_PRESET" "$MODE" "$PRESET_NAME" "$SNAPSHOT_OUT" <<'PY'
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

source = Path(sys.argv[1])
target = Path(sys.argv[2])
control_source = Path(sys.argv[3])
control_target = Path(sys.argv[4])
mode = sys.argv[5]
preset_name = sys.argv[6]
snapshot_out = Path(sys.argv[7]) if sys.argv[7] else None

text = source.read_text(encoding="utf-8")

if mode != "route_follow_only":
    raise SystemExit(f"unsupported planning preset mode: {mode}")

disabled_modules = [
    "launch_crosswalk_module",
    "launch_walkway_module",
    "launch_traffic_light_module",
    "launch_intersection_module",
    "launch_blind_spot_module",
    "launch_detection_area_module",
    "launch_virtual_traffic_light_module",
    "launch_no_stopping_area_module",
    "launch_stop_line_module",
    "launch_occlusion_spot_module",
    "launch_run_out_module",
    "launch_speed_bump_module",
    "launch_dynamic_obstacle_stop_module",
    "launch_out_of_lane_module",
    "launch_obstacle_velocity_limiter_module",
]

updates: dict[str, int] = {}
for module in disabled_modules:
    pattern = re.compile(
        r"(?P<prefix>name:\s*" + re.escape(module) + r"\s*\n\s*default:\s*)\"(?:true|false)\"",
        re.MULTILINE,
    )
    text, count = pattern.subn(r'\g<prefix>"false"', text)
    updates[module] = count

missing = [module for module, count in updates.items() if count == 0]
if missing:
    raise SystemExit(f"planning preset modules not found: {', '.join(missing)}")

header = (
    "# Generated by PIX simctl for route-follow-only CARLA fidelity validation.\n"
    "# Keep traffic-rule scenarios on the default preset; this preset isolates vehicle/control fidelity.\n"
)
target.write_text(header + text, encoding="utf-8")

control_updates: dict[str, int] = {}
control_disabled_modules: list[str] = []
if control_source.exists():
    control_text = control_source.read_text(encoding="utf-8")
    control_disabled_modules = [
        "launch_lane_departure_checker",
        "launch_control_validator",
        "launch_autonomous_emergency_braking",
        "launch_collision_detector",
        "launch_obstacle_collision_checker",
        "launch_predicted_path_checker",
        "launch_control_evaluator",
    ]
    for module in control_disabled_modules:
        pattern = re.compile(
            r"(?P<prefix>name:\s*" + re.escape(module) + r"\s*\n\s*default:\s*)\"(?:true|false)\"",
            re.MULTILINE,
        )
        control_text, count = pattern.subn(r'\g<prefix>"false"', control_text)
        control_updates[module] = count

    missing_control = [module for module, count in control_updates.items() if count == 0]
    if missing_control:
        raise SystemExit(f"control preset modules not found: {', '.join(missing_control)}")

    control_header = (
        "# Generated by PIX simctl for route-follow-only CARLA fidelity validation.\n"
        "# Keep safety-gate scenarios on the default preset; this preset isolates vehicle/control fidelity.\n"
    )
    control_target.write_text(control_header + control_text, encoding="utf-8")

snapshot = {
    "preset_name": preset_name,
    "mode": mode,
    "source_preset": str(source),
    "target_preset": str(target),
    "control_source_preset": str(control_source) if control_source.exists() else None,
    "control_target_preset": str(control_target) if control_source.exists() else None,
    "disabled_modules": disabled_modules,
    "disabled_control_modules": control_disabled_modules,
    "updates": updates,
    "control_updates": control_updates,
}
if snapshot_out is not None:
    snapshot_out.write_text(json.dumps(snapshot, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
print(json.dumps(snapshot, ensure_ascii=False, indent=2))
PY
